apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: loadgpwg1264-tenant-component
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: loadgpwg1264-tenant-component
    app.kubernetes.io/part-of: loadgpwg1264-tenant-app
  name: loadgpwg1264-tenant-component
  namespace: loadgpwg1264-tenant
spec:
  path: /
  port:
    targetPort: 8081
  to:
    kind: Service
    name: loadgpwg1264-tenant-component
    weight: null
status: {}
